apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME
spec:
  selector:
    matchLabels:
      app: $IMAGE_NAME
  template:
    metadata:
      labels:
        app: $IMAGE_NAME
    spec:
      containers:
        - name: nginx
          image: dialogs/prometheus-sending-bot
          command: ["python3", "/tmp/main.py"]
          env:
            - name: FIRST_BOT_TOKEN
              value: $FIRST_BOT_TOKEN
            - name: SECOND_BOT_TOKEN
              value: $SECOND_BOT_TOKEN
            - name: BOT_ENDPOINT
              value: $BOT_ENDPOINT
          ports:
            - containerPort: 8080
apiVersion: v1
kind: Service
metadata:
  labels:
    app: $IMAGE_NAME
  name: $IMAGE_NAME
spec:
  selector:
    app: $IMAGE_NAME
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $IMAGE_NAME
spec:
  rules:
  - http:
     paths:
     - path: /
       backend:
        serviceName: $IMAGE_NAME
        servicePort: 8080
