apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME
spec:
  selector:
    matchLabels:
      app: $IMAGE_NAME
  template:
    metadata:
      labels:
        app: $IMAGE_NAME
    spec:
      containers:
        - name: nginx
          image: $COMPANY_NAME/$IMAGE_NAME
          command: ["python3", "/tmp/main.py"]
          env:
            - name: FIRST_BOT_TOKEN
              value: $FIRST_BOT_TOKEN
            - name: SECOND_BOT_TOKEN
              value: $SECOND_BOT_TOKEN
            - name: BOT_ENDPOINT
              value: $BOT_ENDPOINT
          ports:
            - containerPort: 8080
              name: http

apiVersion: v1
kind: Service
metadata:
  name: $IMAGE_NAME
  namespace: default
  labels:
    app: $IMAGE_NAME
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: $IMAGE_NAME
