apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME
spec:
  selector:
    matchLabels:
      app: $IMAGE_NAME
  template:
    metadata:
      labels:
        app: $IMAGE_NAME
    spec:
      containers:
        - name: nginx
          image: dialogs/prometheus-sending-bot
          command: ["python3", "/tmp/main.py"]
          env:
            - name: FIRST_BOT_TOKEN
              value: $FIRST_BOT_TOKEN
            - name: SECOND_BOT_TOKEN
              value: $SECOND_BOT_TOKEN
            - name: BOT_ENDPOINT
              value: $BOT_ENDPOINT
          ports:
            - containerPort: 8080
